In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Libraries Imported Successfully!")

Matplotlib is building the font cache; this may take a moment.

Libraries Imported Successfully!

In [ ]:
student_data = {
    "StudyHours": [5, 2, 6, 3, 8, 1, 7, 4, 5, 2],
    "Attendance": [90, 60, 95, 75, 98, 40, 88, 70, 85, 55],
    "PreviousMarks": [85, 45, 92, 60, 97, 35, 80, 65, 78, 50],
    "Assignment": ["Yes", "No", "Yes", "Yes", "Yes", "No", "Yes", "Yes", "Yes", "No"],
    "Result": ["Pass", "Fail", "Pass", "Pass", "Pass", "Fail", "Pass", "Pass", "Pass", "Fail"]
}

df = pd.DataFrame(student_data)

df

   StudyHours  Attendance  PreviousMarks Assignment Result
0           5          90             85        Yes   Pass
1           2          60             45         No   Fail
2           6          95             92        Yes   Pass
3           3          75             60        Yes   Pass
4           8          98             97        Yes   Pass
5           1          40             35         No   Fail
6           7          88             80        Yes   Pass
7           4          70             65        Yes   Pass
8           5          85             78        Yes   Pass
9           2          55             50         No   Fail

In [ ]:
df.to_csv("dataset.csv", index=False)

print("Dataset Created Successfully!")

Dataset Created Successfully!

In [ ]:
df.head()

   StudyHours  Attendance  PreviousMarks Assignment Result
0           5          90             85        Yes   Pass
1           2          60             45         No   Fail
2           6          95             92        Yes   Pass
3           3          75             60        Yes   Pass
4           8          98             97        Yes   Pass

In [ ]:
df.shape

(10, 5)

In [ ]:
df.columns

Index(['StudyHours', 'Attendance', 'PreviousMarks', 'Assignment', 'Result'], dtype='str')

In [ ]:
df.info

<bound method DataFrame.info of    StudyHours  Attendance  PreviousMarks Assignment Result
0           5          90             85        Yes   Pass
1           2          60             45         No   Fail
2           6          95             92        Yes   Pass
3           3          75             60        Yes   Pass
4           8          98             97        Yes   Pass
5           1          40             35         No   Fail
6           7          88             80        Yes   Pass
7           4          70             65        Yes   Pass
8           5          85             78        Yes   Pass
9           2          55             50         No   Fail>

In [ ]:
df.describe

<bound method NDFrame.describe of    StudyHours  Attendance  PreviousMarks Assignment Result
0           5          90             85        Yes   Pass
1           2          60             45         No   Fail
2           6          95             92        Yes   Pass
3           3          75             60        Yes   Pass
4           8          98             97        Yes   Pass
5           1          40             35         No   Fail
6           7          88             80        Yes   Pass
7           4          70             65        Yes   Pass
8           5          85             78        Yes   Pass
9           2          55             50         No   Fail>

In [ ]:
df.isnull().sum()

StudyHours       0
Attendance       0
PreviousMarks    0
Assignment       0
Result           0
dtype: int64

In [ ]:
df.shape
df.columns
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   StudyHours     10 non-null     int64
 1   Attendance     10 non-null     int64
 2   PreviousMarks  10 non-null     int64
 3   Assignment     10 non-null     str
 4   Result         10 non-null     str
dtypes: int64(3), str(2)
memory usage: 532.0 bytes

StudyHours       0
Attendance       0
PreviousMarks    0
Assignment       0
Result           0
dtype: int64

In [ ]:
plt.figure(figsize=(6,4))
plt.bar(df.index, df["StudyHours"], color="skyblue")

plt.title("Study Hours of Students")
plt.xlabel("Student ID")
plt.ylabel("Study Hours")

plt.show()